apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "laravel.fullname" . }}-sqlite
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.persistence.sqliteSize }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "laravel.fullname" . }}-storage
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.persistence.storageSize }}
