apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "laravel.fullname" . }}-env
data:
  APP_ENV: {{ .Values.appEnv }}
  APP_DEBUG: {{ .Values.appDebug | quote }}
  APP_URL: {{ .Values.appUrl }}
  DB_CONNECTION: {{ .Values.dbConnection }}
  LOG_CHANNEL: {{ .Values.logChannel }}
  SESSION_DRIVER: {{ .Values.sessionDriver }}
